language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

env:
  global:
  - WORKSPACE=SparkSDK.xcworkspace
  - SCHEME=SparkSDK
  matrix:
    - DESTINATION="OS=10.0,name=iPhone 6s"      CONFIGURATION="Debug"
    - DESTINATION="OS=10.0,name=iPhone 6s"      CONFIGURATION="ReleaseTest"

script:
  - set -o pipefail
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration "$CONFIGURATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clientSecret="$CLIENTSECRET" test | xcpretty -c

branches:
  only:
    - swift3
